### PR TITLE
chore(testnet-runtime): v0.4.2

### PR DESCRIPTION
**Pull request by al3mart**
Ready release for `pop-runtime-testnet` version `0.4.2`

### CODE REVIEW

**Comment by al3mart** [comment]
> Missing matching version bump in testnet runtime manifest.

Nice cath! :pray: Addressed in [ed83838](https://github.com/r0gue-io/pop-node/pull/369/commits/ed8383877978be95319d187b366f4253b6a1ef20)

**Review by AlexD10S — APPROVED** [review]
Everything looks good to me, and all tests passed successfully!

**Comment by al3mart** [comment]
> Why wasnt https://github.com/r0gue-io/pop-node/blob/main/.github/ISSUE_TEMPLATE/release_tracking.md used?

Appreciate the reminder, please find the tracking issue in: https://github.com/r0gue-io/pop-node/issues/372

**Review by Daanvdplas — APPROVED** [review]
LGTM!

**Review by evilrobot-01 — APPROVED** [review]
Cant see anything obvious that still needs addressing.

**Pull request merged**
